"""empty message

Revision ID: a03164774a4d
Revises: dde9d60420e5
Create Date: 2021-08-08 13:03:36.918047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03164774a4d'
down_revision = 'dde9d60420e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrafficCam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validOffences', sa.String(length=20), nullable=False),
    sa.Column('locationID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locationID'], ['Location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrafficCam')
    # ### end Alembic commands ###
