"""empty message

Revision ID: dde9d60420e5
Revises: 
Create Date: 2021-08-07 22:32:45.276290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde9d60420e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('parish', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Offence',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('fine', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('paymentDuration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('isAdmin', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Vehicle',
    sa.Column('licenseplate', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('make', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('colour', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('licensediscno', sa.String(length=60), nullable=False),
    sa.Column('cartype', sa.String(length=60), nullable=False),
    sa.Column('expdate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('licenseplate')
    )
    op.create_table('Incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('locationID', sa.Integer(), nullable=False),
    sa.Column('offenceID', sa.String(length=4), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['locationID'], ['Location.id'], ),
    sa.ForeignKeyConstraint(['offenceID'], ['Offence.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VehicleOwner',
    sa.Column('trn', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('fname', sa.String(length=25), nullable=False),
    sa.Column('lname', sa.String(length=25), nullable=False),
    sa.Column('mname', sa.String(length=25), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('parish', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('licenseplate', sa.String(length=20), nullable=False),
    sa.Column('licensein', sa.String(length=10), nullable=False),
    sa.Column('expdate', sa.Date(), nullable=False),
    sa.Column('licenseType', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['licenseplate'], ['Vehicle.licenseplate'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trn')
    )
    op.create_table('FlaggedEmail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trn', sa.String(length=10), nullable=False),
    sa.Column('incidentID', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['incidentID'], ['Incident.id'], ),
    sa.ForeignKeyConstraint(['trn'], ['VehicleOwner.trn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incidentID')
    )
    op.create_table('FlaggedImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidentID', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['incidentID'], ['Incident.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incidentID')
    )
    op.create_table('IssuedTicket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trn', sa.String(length=10), nullable=False),
    sa.Column('incidentID', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['incidentID'], ['Incident.id'], ),
    sa.ForeignKeyConstraint(['trn'], ['VehicleOwner.trn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incidentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IssuedTicket')
    op.drop_table('FlaggedImage')
    op.drop_table('FlaggedEmail')
    op.drop_table('VehicleOwner')
    op.drop_table('Incident')
    op.drop_table('Vehicle')
    op.drop_table('User')
    op.drop_table('Offence')
    op.drop_table('Location')
    # ### end Alembic commands ###
