"""empty message

Revision ID: e17aa505c5f6
Revises: a03164774a4d
Create Date: 2021-08-08 14:38:05.195110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17aa505c5f6'
down_revision = 'a03164774a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArchivedTicket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidentID', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['incidentID'], ['Incident.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incidentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ArchivedTicket')
    # ### end Alembic commands ###
